#pragma once
const int RF_SENSOR_KOTELNA_INTERNAL_TEMPERATURE_ID = 1;
const int RF_SENSOR_KOTELNA_SMOKE_TEMPERATURE_ID = 2;
const int RF_SENSOR_KOTELNA_OUTPUT_TEMPERATURE_ID = 3;
const int RF_SENSOR_KOTELNA_RETURN_TEMPERATURE_ID = 4;

const byte RF_KOTELNA_ADDRESS[] = "sensorKotelna";
