#pragma once
const int RF_SENSOR_KOTELNA_INTERNAL_TEMPERATURE_ID = 1;
const int RF_SENSOR_KOTELNA_SMOKE_TEMPERATURE_ID = 2;
const int RF_SENSOR_KOTELNA_OUTPUT_TEMPERATURE_ID = 3;
const int RF_SENSOR_KOTELNA_RETURN_TEMPERATURE_ID = 4;

const int RF_SENSOR_OUTSIDE_TEMPERATURE_ID = 10;

const uint64_t RF_KOTELNA_ADDRESS = 0xE8E8F0F0A1LL;
const uint64_t RF_OUTSIDE_ADDRESS = 0xE8E8F0F0B2LL;
